---@class senpai.ChatWindow.Config
---@field provider provider
---@field provider_config senpai.Config.providers.Provider
---@field system_prompt string
---@field thread_id string
---@field chat_log NuiSplit|nil
---@field chat_input NuiSplit|nil
---@field hidden boolean
